### ISSUE TITLE
CDN appears to be down

### ISSUE THREAD

**Issue by fenomas** [Tonejs/CDN#1]
I get `404 - There isn't a GitHub Pages site here.` errors for all pages, including http://cdn.tonejs.org/. 

Is this just me?

**Comment by tambien** [comment]
oh! I forgot to update the README but I've moved away from cdn.tonejs.org and to tonejs.github.io/CDN because the latter supports SSL so you can include the link on https websites.

**Comment by fenomas** [comment]
Okie doke, I'll ping the project I saw using the old URL.
